### ISSUE TITLE
前端如果用vue，为何不尝试用Element

### ISSUE THREAD

**Issue by TonnyGu** [holmescn/CoreCRM#3]
http://element.eleme.io/#/zh-CN

**Comment by holmescn** [comment]
@TonnyGu 谢谢，我去看一下。

**Comment by TonnyGu** [comment]
@holmescn 有没有设计原型或者规划什么的？

**Comment by holmescn** [comment]
@TonnyGu 设计原型是参考 悟空CRM，这个有开源版，也有一个在线版。在线版可以免费注册。我主要是参考在线版。因为在线版的完成度比开源版要好很多。

不过在主要架构完成之后， UI 部分会重新设计。开发没有规划，因为我现在时间没有保证。

**Comment by holmescn** [comment]
@TonnyGu 由于新成员的加入，前端改用了 React 和 Ant Design。所以这个 issue 就关闭了。
